### ISSUE TITLE
Crash after running over an entire brick

### ISSUE THREAD

**Issue by ngbusca** [julienguy/redlantern#1]
After running without multiprocessing over brick brick-b-4200p000.fits brick-r-4200p000.fits of the BOSS quasar training sample, I get a crash at the very end, after seemingly successfully fitting over all spectra.

I can't reproduce the bug if I run only over a few spectra in this brick.

Traceback (most recent call last):
  File "/Users/ngbusca/Boulot/DESI/github/desispec/bin/desi_zfind", line 8, in <module>
    zfind.main(args)
  File "/Users/ngbusca/Boulot/DESI/github/desispec/py/desispec/scripts/zfind.py", line 199, in main
    zff = RedMonsterZfind(**arg)
  File "/Users/ngbusca/Boulot/DESI/github/desispec/py/desispec/zfind/redmonster.py", line 113, in **init**
    self.zpicker = ZPicker(specobj, self.zfinders, self.zfitters, flags)
  File "/Volumes/LyA4ToB/ngbusca/DESI/redmonster/python/redmonster/physics/zpicker2.py", line 65, in **init**
    self.classify_obj(zfindobjs, zfitobjs, flags)
  File "/Volumes/LyA4ToB/ngbusca/DESI/redmonster/python/redmonster/physics/zpicker2.py", line 140, in classify_obj
    n.max(zfitobjs[itemp].chi2vals[ifiber]) / \
  File "/Users/ngbusca/Boulot/homebrew/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2258, in amax
    out=out, keepdims=keepdims)
  File "/Users/ngbusca/Boulot/homebrew/lib/python2.7/site-packages/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation maximum which has no identity

**Comment by julienguy** [comment]
ok, checking that ...

**Comment by julienguy** [comment]
I have the same error ... I am going to rerun with temporary much shorter template arrays to go faster

**Comment by ngbusca** [comment]
@julienguy Can we predict which spectra cause trouble and skip them in the wrapper?

**Comment by julienguy** [comment]
This is now fixed in the head version.
There was a bug when no solution was found for one template class (for instance, no valid solution for stars but solutions for QSO and galaxies). I checked that the best solution is found at the end in those cases.

**Comment by julienguy** [comment]
I processed brick 4200p000 in 38 minutes on 20 cores with the original redmonster templates.
